---
description: launch a VM, build Docker and run tests
enabled: true
entry_point: everything.py
name: build_n_test
runner_type: run-python
notify:
  on-success:
    routes:
      - slackbuild
    message:
      "{% for suite, results in action_results.result['res'].items() %}
          {{ suite }}: `
          {% for  k, v in results.items() %}
            {{ k|lower }} {{ v }}
          {% endfor %} `
       {% endfor %}"
    data:
      channel: '#github'
      username: 'nightly-build'
  on-failure:
    routes:
      - slackbuild
    message: 'Build fails'
    data:
      channel: '#github'
      username: 'nightly-build'
