---
description: launch a VM, build Docker and run tests
enabled: true
entry_point: everything.py
name: build_n_test
runner_type: run-python
notify:
  on-success:
    routes:
      - slack_build
    message: 'Nightly build is finished'
    data:
      channel: '#dev'
  on-failure:
    routes:
      - slack_build
    message: 'Nightly build fails'
    data:
      channel: '#dev'
