name: build.concurrency
description: Limits concurrent openioci.build executions.
enabled: true
resource_ref: openioci.build
policy_type: action.concurrency
parameters:
    action: delay
    threshold: 4

